version: "3.3"
services:
  frontend_dev:
    container_name: react_ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command:
      - /bin/sh
      - -c
      - |
        yarn upgrade
        yarn start
    ports:
      - 3000:3000
    environment:
      - TZ=${TZ}
